void make(Graph G)
{List tmp;
G[0]->Next=NULL;
G[0]->V=0;
G[0]->w=0;
tmp=G[1];
tmp->V=1;
tmp->w=2;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=4;
tmp->w=16;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=12;
tmp->w=39;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=16;
tmp->w=99;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=28;
tmp->Next=NULL;
tmp=G[2];
tmp->V=2;
tmp->w=43;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=10;
tmp->w=68;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=13;
tmp->w=58;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=29;
tmp->Next=NULL;
tmp=G[3];
tmp->V=3;
tmp->w=25;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=2;
tmp->w=43;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=5;
tmp->w=82;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=6;
tmp->w=99;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=13;
tmp->w=40;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=14;
tmp->w=26;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=19;
tmp->w=37;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=21;
tmp->w=27;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=30;
tmp->Next=NULL;
tmp=G[4];
tmp->V=4;
tmp->w=72;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=9;
tmp->w=39;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=16;
tmp->w=33;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=21;
tmp->w=39;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=22;
tmp->w=33;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=23;
tmp->w=84;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=28;
tmp->Next=NULL;
tmp=G[5];
tmp->V=5;
tmp->w=52;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=4;
tmp->w=94;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=8;
tmp->w=89;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=21;
tmp->w=63;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=23;
tmp->w=62;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=25;
tmp->Next=NULL;
tmp=G[6];
tmp->V=6;
tmp->w=28;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=7;
tmp->w=8;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=22;
tmp->Next=NULL;
tmp=G[7];
tmp->V=7;
tmp->w=11;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=15;
tmp->w=23;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=27;
tmp->w=21;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=30;
tmp->Next=NULL;
tmp=G[8];
tmp->V=8;
tmp->w=45;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=3;
tmp->w=42;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=17;
tmp->w=47;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=19;
tmp->w=55;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=23;
tmp->Next=NULL;
tmp=G[9];
tmp->V=9;
tmp->w=18;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=17;
tmp->w=38;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=20;
tmp->w=0;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=22;
tmp->w=18;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=24;
tmp->Next=NULL;
tmp=G[10];
tmp->V=10;
tmp->w=37;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=15;
tmp->w=86;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=22;
tmp->w=2;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=30;
tmp->Next=NULL;
tmp=G[11];
tmp->V=11;
tmp->w=20;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=27;
tmp->Next=NULL;
tmp=G[12];
tmp->V=12;
tmp->w=65;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=4;
tmp->w=42;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=17;
tmp->w=73;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=19;
tmp->Next=NULL;
tmp=G[13];
tmp->V=13;
tmp->w=49;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=1;
tmp->w=2;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=5;
tmp->w=11;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=9;
tmp->Next=NULL;
tmp=G[14];
tmp->V=14;
tmp->w=51;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=5;
tmp->w=43;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=13;
tmp->w=72;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=24;
tmp->Next=NULL;
tmp=G[15];
tmp->V=15;
tmp->w=47;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=2;
tmp->Next=NULL;
tmp=G[16];
tmp->V=16;
tmp->w=91;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=27;
tmp->Next=NULL;
tmp=G[17];
tmp->V=17;
tmp->w=16;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=8;
tmp->w=80;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=13;
tmp->w=55;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=14;
tmp->w=24;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=28;
tmp->w=68;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=30;
tmp->Next=NULL;
tmp=G[18];
tmp->V=18;
tmp->w=74;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=6;
tmp->w=69;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=21;
tmp->w=40;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=25;
tmp->Next=NULL;
tmp=G[19];
tmp->V=19;
tmp->w=40;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=13;
tmp->w=44;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=24;
tmp->Next=NULL;
tmp=G[20];
tmp->V=20;
tmp->w=9;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=9;
tmp->w=8;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=17;
tmp->w=89;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=22;
tmp->Next=NULL;
tmp=G[21];
tmp->V=21;
tmp->w=74;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=16;
tmp->Next=NULL;
tmp=G[22];
tmp->V=22;
tmp->w=50;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=8;
tmp->w=2;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=9;
tmp->Next=NULL;
tmp=G[23];
tmp->V=23;
tmp->w=3;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=4;
tmp->w=13;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=9;
tmp->w=33;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=17;
tmp->w=62;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=25;
tmp->Next=NULL;
tmp=G[24];
tmp->V=24;
tmp->w=24;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=9;
tmp->w=44;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=25;
tmp->w=53;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=28;
tmp->Next=NULL;
tmp=G[25];
tmp->V=25;
tmp->w=56;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=4;
tmp->w=51;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=5;
tmp->w=21;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=11;
tmp->w=72;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=12;
tmp->w=91;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=14;
tmp->w=80;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=15;
tmp->w=30;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=16;
tmp->w=6;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=24;
tmp->Next=NULL;
tmp=G[26];
tmp->V=26;
tmp->w=40;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=3;
tmp->w=21;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=4;
tmp->w=54;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=14;
tmp->w=65;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=30;
tmp->Next=NULL;
tmp=G[27];
tmp->V=27;
tmp->w=77;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=10;
tmp->w=73;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=12;
tmp->w=93;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=28;
tmp->Next=NULL;
tmp=G[28];
tmp->V=28;
tmp->w=63;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=11;
tmp->w=89;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=30;
tmp->Next=NULL;
tmp=G[29];
tmp->V=29;
tmp->w=40;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=11;
tmp->w=50;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=12;
tmp->w=30;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=27;
tmp->Next=NULL;
tmp=G[30];
tmp->V=30;
tmp->w=38;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=2;
tmp->w=98;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=8;
tmp->w=35;
tmp=(tmp->Next=(List)malloc(sizeof(struct Node)));
tmp->V=25;
tmp->Next=NULL;
}